use coffee_db;
select*from coffeesales;
/*TOTAL SALES FROM SALE AND PROFIT*/
SELECT
SUM(SALES)AS TOT_SALES,
SUM(PROFIT)AS TOT_PROF
FROM COFFEESALES;

/*SALES BY REGION*/
SELECT STATE,SUM(SALES)AS TOT_SALES
FROM COFFEESALES
GROUP BY STATE
ORDER BY TOT_SALES DESC
LIMIT 0,500;

/*TOP 5PROFIT AND PRODUCT */

SELECT PRODUCT,SUM(PROFIT)AS TOT_PRO
FROM COFFEESALES
GROUP BY product
ORDER BY TOT_PRO DESC
LIMIT 5;

/*SALES BY PRODUCT TYPE*/
SELECT PRODUCTYPE,SUM(sALES)AS TOTA_SAL
FROM COFFEESALES
GROUP BY PRODUCTYPE
ORDER BY TOTA_SAL DESC;

/*MONTHLY SALES TREND*/
SELECT 
	DATE_FORMAT(DATE,'%Y-%M')AS MONTH,
	SUM(SALES)AS TOT_SALE
FROM COFFEESALES
GROUP BY MONTH
ORDER BY MONTH;

/*PROFIT MARGIN FOR EACH PRODUCT*/
SELECT 
PRODUCT,
SUM(PROFIT)/NULLIF(SUM(SALES),0)AS PROFIT_MARGIN
FROM COFFEESALES
GROUP BY PRODUCT     
ORDER BY PROFIT_MARGIN DESC;

/*FIND PRPFIT WITH NEGATIVE PROFIT*/
SELECT PRODUCT,SUM(PROFIT) AS TOTA_PRO
FROM COFFEESALES
GROUP BY PRODUCT 
HAVING TOTA_PRO <0;

/*TOP 3 SALES BY PROFIT*/

SELECT SALES,SUM(PROFIT) AS TOTA_PRO
FROM COFFEESALES
GROUP BY SALES
ORDER BY TOTA_PRO DESC
LIMIT 3;

/*TOP  SATES BY PROFIT */
SELECT STATE, SUM(PROFIT)AS TOTA_PROF
FROM COFFEESALES
GROUP BY STATE
ORDER BY TOTA_PROF DESC
LIMIT 3;